### ISSUE TITLE
fix: Wrong polish native name

### ISSUE THREAD

**Issue by SeriousMonk** [tsinis/sealed_world#221]
Currently 
```dart 
print(NaturalLanguage.fromCodeShort('pl').namesNative);
```
prints ```[polszczyzna]``` which is wrong and should be ```[Polski]```.

**Comment by tsinis** [comment]
Hey @SeriousMonk!

Thanks, but actually it's not wrong, you can check for example the [Polish Wikipedia](https://pl.wikipedia.org/wiki/J%C4%99zyk_polski#:~:text=J%C4%99zyk%20polski%2C%20polszczyzna) or website of the [Polish Ministry of National Education](https://zpe.gov.pl/a/polszczyzna-niejedno-ma-imie-terytorialne-zawodowe-i-srodowiskowe-odmiany-wspolczesnego-jezyka-polskiego/D17EgtYEO). Both "język polski" and "polszczyzna" are correct, it's very same as in other (not only Western) Slavic languages (i.e. Czech "čeština" == "český jazyk" or Slovak "slovenčina" == "slovenský jazyk").

Anyway, I will probably add "język polski" to the `namesNative` array too in the next `sealed_languages` release :). Thanks again for your feedback, I appreciate it a lot!

**Comment by SeriousMonk** [comment]
Hey,

Yes it exists, but Polszczyzna is used in a different context (eg when you talk about the language in grammar for instance). 

When one is looking for the language on a website for example, no one ever will search for Polszczyzna, but they will look for Polski. 
It will probably be the same for other Slavic languages as well.

Polszczyzna can still be there if needed, but in my opinion Polski should be in first place among the namesNative.

Btw I am polish :)

**Comment by tsinis** [comment]
Sure @SeriousMonk, as I mentioned, I will add "język polski" or just "polski" to that array in the next release. From the UX/UI POV, right now, when users start writing "pol" (so no matter if it's "polski" or "polszczyzna") in the Flutter language picker it will find the only language - "Polish" :) Dzięki!

<img width="896" alt="image" src="https://github.com/user-attachments/assets/f080943d-d530-4ff8-90f2-099024a8c126">

**Comment by tsinis** [comment]
Hey, @SeriousMonk just letting you know - this was addressed in the [sealed_languages v1.5.1](https://pub.dev/packages/sealed_languages/changelog), thanks for your feedback again!
